name: mini_tourist
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  http: ^1.1.0
  fan_carousel_image_slider: any
  widget_slider: ^0.1.0
  path_provider: ^2.0.14
  image_gallery_saver: ^2.0.3
  fluttertoast: ^8.2.6
  flutter_rating_bar: ^4.0.1
  intl: ^0.17.0
  carousel_slider: ^5.1.1
  flutter_svg: ^2.0.7
  font_awesome_flutter: ^10.7.0
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  image_picker: ^1.1.2
  shared_preferences: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/images/
